import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { GeistSans } from 'geist/font/sans';  
import './globals.css'
import Home from './page';
import Navbar from '@/components/navbar';


export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${GeistSans.className} antialiased`}>
           <Navbar />
            {/*// <SignedOut> */}
            {/* <Home /> */}
            {/* </SignedOut>
            <SignedIn>
              <UserButton /> */}
          {children}
            {/* </SignedIn> */}
        </body>
      </html>
    </ClerkProvider>
  )
}